### ISSUE TITLE
Práctica 5 finaliza. Duda reto. Pablo Bethencourt

### ISSUE THREAD

**Issue by alu0100658705** [ULL-ESIT-DSI-1920/dsi-p5-mkart-alu0100658705#1]
Buenas tardes @ManzDev ,

He finalizado la práctica 5 añadiendo el reto, eso sí, para el reto, modifiqué el valor del intervalo y en vez de ir a 60fps, se desplaza cada 0.5 segundos, esto lo cambié puesto que sino no se me veía el item (o iteraba de forma exagerada). No obstante tengo el problema de que muchas veces la acción del item que aparece en pantalla no corresponde con la que toma el Kart. No sé como podría solventarlo. En caso de ser muy complicado o tener que realizar muchas modificaciones, entregaría ya la práctica en este estado. Aunque me gustaría retocarla, tengo demasiado trabajo con otras asignaturas + TFG :( .

Muchas Gracias. Saludos.

**Comment by ManzDev** [comment]
Hola Pablo,

No te preocupes por el tema de los FPS y demás, puesto que eso puede ser debido a que no es la mejor forma de hacer un juego de este tipo. Las maneras habituales suelen ser utilizar <canvas> y programación gráfica, pero el objetivo de la práctica era ver los contenidos del tema de una forma "práctica y entretenida".

No obstante, veo que has hecho buen uso de los WebComponents, utilizas los diferentes aspectos como shadow dom, buen uso de las clases y demás. Además, de haber implementado el reto de los items del kart, por lo que tienes un APTO+ en la práctica.

A por las siguientes!
Saludos,
